version: "3.9"

services:
  postgres:
    image: postgres:16-alpine
    container_name: bot_postgres
    environment:
      POSTGRES_USER: bot
      POSTGRES_PASSWORD: botpass
      POSTGRES_DB: botdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U bot -d botdb"]
      interval: 5s
      timeout: 5s
      retries: 10

  n8n:
    image: n8nio/n8n:latest
    container_name: bot_n8n
    ports:
      - "5678:5678"
    environment:
      N8N_BASIC_AUTH_ACTIVE: "true"
      N8N_BASIC_AUTH_USER: "admin"
      N8N_BASIC_AUTH_PASSWORD: "admin123"

      N8N_HOST: "${N8N_HOST}"
      N8N_PORT: "5678"
      N8N_PROTOCOL: "${N8N_PROTOCOL}"

      GENERIC_TIMEZONE: "America/Guatemala"

      N8N_EDITOR_BASE_URL: "${N8N_BASE_URL}"
      WEBHOOK_URL: "${N8N_BASE_URL}"
    volumes:
      - n8n_data:/home/node/.n8n
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

  fastapi:
    build:
      context: ./fastapi
    container_name: bot_fastapi
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: "postgresql+psycopg://bot:botpass@postgres:5432/botdb"
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

volumes:
  pgdata:
  n8n_data:
